Controllers/ConsultationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cosultations.Models;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Entities;
using Services.Services;

namespace Cosultations.Controllers
{
    public class ConsultationController : Controller
    {
        private readonly ConsultatiiServices consultatiiServices;
        private readonly CurrentUser currentUser;
        public ConsultationController(ConsultatiiServices consultatiiServices, CurrentUser currentUser)
        {
            this.currentUser = currentUser;
            this.consultatiiServices = consultatiiServices;

        }
        public IActionResult Index(string Nume)
        {
            var model = new IndexConsultatiiVm();
            if (currentUser.IsAuthenticated)
            {
                if (Nume == null)
                {
                    var consultatii = consultatiiServices.GetAll();
                    model.listaConsultatii = consultatii;
                    return View(model);
                }
                else
                {
                    var consultatii = consultatiiServices.GetAllByNameP(Nume);
                    model.listaConsultatii = consultatii;
                    return View(model);
                }
            }
            else return NotFound();
        }
       
        public IActionResult SeeServices(int Id)
        {
            if (currentUser.IsAuthenticated)
            {
                var services = consultatiiServices.TakeServicesByConsultationId(Id);
                return View(services);
            }
            else return NotFound();
        }

        public IActionResult DetailsAboutConsultation(int Id)
        {
            if (currentUser.IsAuthenticated)
            {
                var model = consultatiiServices.TakeAllDetails(Id);
                return View(model);
            }
            else return NotFound();
        }

        
        

      
    }
}

Controllers/ServiciuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Services.Services;

namespace Cosultations.Controllers
{
    public class ServiciuController : Controller
    {
        private readonly ServiciiServices serviciiServices;
        public ServiciuController(ServiciiServices serviciiServices)
        {
            this.serviciiServices = serviciiServices;
        }
        public IActionResult Index()
        {
            var model = serviciiServices.GetAll();
            return View(model);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @inject Services.CurrentUser CurrentUser
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Consultations</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Consultation" asp-action="Index">Consultatii</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (CurrentUser.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Medic" asp-action="Index">Medici</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pacient" asp-action="Index">Pacienti</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Specializare" asp-action="Index">Specializari</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Serviciu" asp-action="Index">Servicii</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Medic" asp-action="IndexFilter">Statistica medie</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">LogOut</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Cosultations 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>